apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-rooms-texture-detailer-vol
  namespace: undergrad-ms
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 256Gi
  