apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod
  namespace: undergrad-ms
  labels:
    app: gpu-pod
spec:
  containers:
  - name: sam3d-container
    image: nvidia/cuda:12.1.0-devel-ubuntu22.04
    command: ["sleep", "infinity"]
    resources:
      limits:
        nvidia.com/gpu: 1
        cpu: "4"
        memory: 16Gi
      requests:
        nvidia.com/gpu: 1
        cpu: "2"
        memory: 8Gi
    volumeMounts:
    - name: data-volume
      mountPath: /workspace
    env:
    - name: DEBIAN_FRONTEND
      value: "noninteractive"
    - name: CUDA_HOME
      value: "/usr/local/cuda"
    - name: CONDA_PREFIX
      value: "/usr/local/cuda"
  volumes:
  - name: data-volume
    persistentVolumeClaim:
      claimName: open-rooms-texture-detailer-vol
  restartPolicy: Always
