apiVersion: v1
kind: Pod
metadata:
  name: setup-pod
  namespace: undergrad-ms
  labels:
    app: setup-pod
spec:
  containers:
  - name: setup-container
    image: ubuntu:22.04
    command: ["sleep", "infinity"]
    resources:
      limits:
        cpu: "2"
        memory: 8Gi
      requests:
        cpu: "100m"
        memory: 500Mi
    volumeMounts:
    - name: data-volume
      mountPath: /workspace
    env:
    - name: DEBIAN_FRONTEND
      value: "noninteractive"
  volumes:
  - name: data-volume
    persistentVolumeClaim:
      claimName: open-rooms-texture-detailer-vol
  restartPolicy: Always
